// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFSG53rKCja9GI3ATl7OaXelN-Zrrw-zE',
    appId: '1:927379543776:web:05fc511b23313650c62285',
    messagingSenderId: '927379543776',
    projectId: 'chat-app-38a5f',
    authDomain: 'chat-app-38a5f.firebaseapp.com',
    storageBucket: 'chat-app-38a5f.appspot.com',
    measurementId: 'G-KZMZ7QEFXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTWiyIowI2hbUvlbzBJJFhKQKlig3nV48',
    appId: '1:927379543776:android:1529150325a90c3cc62285',
    messagingSenderId: '927379543776',
    projectId: 'chat-app-38a5f',
    storageBucket: 'chat-app-38a5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb5EJxT5o1vieszfYEOhw7iiooqjz5O-s',
    appId: '1:927379543776:ios:3a5373e74eb0ee60c62285',
    messagingSenderId: '927379543776',
    projectId: 'chat-app-38a5f',
    storageBucket: 'chat-app-38a5f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb5EJxT5o1vieszfYEOhw7iiooqjz5O-s',
    appId: '1:927379543776:ios:3a5373e74eb0ee60c62285',
    messagingSenderId: '927379543776',
    projectId: 'chat-app-38a5f',
    storageBucket: 'chat-app-38a5f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFSG53rKCja9GI3ATl7OaXelN-Zrrw-zE',
    appId: '1:927379543776:web:0ec4252e216a3618c62285',
    messagingSenderId: '927379543776',
    projectId: 'chat-app-38a5f',
    authDomain: 'chat-app-38a5f.firebaseapp.com',
    storageBucket: 'chat-app-38a5f.appspot.com',
    measurementId: 'G-8GX06C2LZ8',
  );
}
